apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-scheduler
  namespace: gpu-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-scheduler-role
subjects:
  - kind: ServiceAccount
    name: gpu-scheduler
    namespace: gpu-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---

apiVersion: v1
kind: Service
metadata:
  name: gpu-scheduler-svc
  namespace: gpu-system
  labels:
    app: gpu-scheduler
spec:
  type: ClusterIP
  ports:
    - port: 3456
      targetPort: 3456
  selector:
    app: gpu-scheduler
---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  name: gpu-scheduler
  namespace: gpu-system
spec:
  replicas: {{.replicas}}
  selector:
    matchLabels:
      app: gpu-scheduler
  template:
    metadata:
      labels:
        app: gpu-scheduler
    spec:
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              weight: 1
      serviceAccount: gpu-scheduler
      containers:
        - image: {{.repo}}gpu-scheduler:v1.2.0 #registry.cn-hangzhou.aliyuncs.com/bocloud/gpu-scheduler:v1.2.0
          imagePullPolicy: Always
          name: gpu-scheduler
          ports:
            - containerPort: 3456
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 400m
          volumeMounts:
            - name: config
              mountPath: /etc/gpu-config
      volumes:
        - name: config
          configMap:
            name: gpu-custom-config
      dnsPolicy: ClusterFirstWithHostNet
      priority: 2000000000
      hostNetwork: false
      priorityClassName: system-cluster-critical