---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-admission
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-admission-role
subjects:
- kind: ServiceAccount
  name: gpu-admission
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  name: gpu-admission
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-admission
  template:
    metadata:
      labels:
        app: gpu-admission
    spec:
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            weight: 1
      serviceAccount: gpu-admission
      serviceAccountName: gpu-admission
      containers:
      - image: {{ .repo }}gpu-admission:1.1
        imagePullPolicy: IfNotPresent
        name: gpu-admission
        env:
        - name: LOG_LEVEL
          value: "1"
        ports:
        - containerPort: 3456
        resources:
          requests:
            memory: 64Mi
            cpu: 200m
          limits:
            memory: 128Mi
            cpu: 400m
      dnsPolicy: ClusterFirstWithHostNet
      priority: 2000000000
      hostNetwork: true
      priorityClassName: system-cluster-critical
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-admission-svc
  namespace: kube-system
  labels:
    app: gpu-admission
spec:
  type: ClusterIP
  ports:
    - port: 3456
      targetPort: 3456
  selector:
    app: gpu-admission
