apiVersion: scheduling.k8s.io/v1
description: high priority used by board application of aios
globalDefault: false
kind: PriorityClass
metadata:
  name: board-high
value: 10000
---
apiVersion: scheduling.k8s.io/v1
description: low priority used by board application of aios
globalDefault: false
kind: PriorityClass
metadata:
  name: board-low
value: 100
---
apiVersion: scheduling.k8s.io/v1
description: medium priority used by board application of aios
globalDefault: false
kind: PriorityClass
metadata:
  name: board-med
value: 1000
