apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: controller-config
  namespace: gpu-system
data:
  maintainer-rule.yaml: |
    # maintainer 配置规则
    maintainer:
    - type: "driver"                   #给哪个maintainer读取用的
      imageRepo: ""                    #镜像公用前缀
      arch-support:                    #支持的架构,如架构不匹配将导致当前maintainer返回invalid
      - "amd64"
      - "arm64"
      vendor-support:                  #支持的产品，如产品不支持将导致当前maintainer被skip
      - "NVIDIA"
      - "ASCEND"
      images:                          #不同vendor下的不同镜像
      - name: "driver-maintainer"      #镜像name
        tag: "1.0.0"                   #镜像版本
        vendor: "NVIDIA"               #适用vendor (正则)
      mountPath:                       #额外挂载信息
      - host: "/root/binary/Linux.run" #主机目录
        path: "/driver.run"            #容器目录
        node: ".*"                     #适用节点 (正则)  
      - host: "/etc/os-release"
        path: "/etc/os-release"
        node: ".*"
      - host: "/lib/modules"
        path: "/lib/modules"
        node: ".*"
      - host: "/dev"
        path: "/dev/host"
        node: ".*"        
      - host: "/usr/src"
        path: "/usr/src"
        node: ".*"
      - host: "/usr"
        path: "/usr/host"
        node: ".*"
      - host: "/var/log"
        path: "/var/log"
        node: ".*"
        

  reconciler-rule.yaml: |
    capacity:
    - vendor: "NVIDIA"
      name: "vcuda-rule"
      rules:
      - type: "VGPU"
        key: "bocloud.com/vcuda-core"
        value: 100
      - type: "VGPU"
        key: "bocloud.com/vcuda-memory"
        valueFrom:
          key: ".productInfo.memory"       # jsonpath
      - type: "MIG"
        keyFrom:
          key: ".name"                       # jsonpath
        value: 1
    - vendor: "HYGON"
      name: "hygon-rule"
      rules:
      - type: "VGPU"
        key: "hygon.com/dcu"
        value: 1
      - type: "MIG"
        key: "hygon.com/dcu-share"
        value: 4
    - vendor: "DL"
      name: "DL-rule"
      rules:
      - type: "VGPU"
        key: "denglinai.com/gpu"
        value: 1
    - vendor: "TS"
      name: "TS-rule"
      rules:
      - type: "VGPU"
        key: "iluvatar.ai/gpu"
        value: 1
    - vendor: "ASCEND"
      name: "ASCEND-rule"
      rules:
        - type: "MIG"
          key: "huawei.com/"
          value: 1
        - type: "VGPU"
          key: "huawei.com/"
          value: 1
  vendors.yaml: |
    vendors:
    - name: "NVIDIA"
      cardType: "GPU"
      id: "10DE"
    - name: "ASCEND"
      cardType: "NPU"
      id: "19E5"
    - name: "HYGON"
      cardType: "DCU"
      id: "1D94"
    - name: "AMD"
      cardType: "GPU"
      id: "1002"
    - name: "DL"
      cardType: "GPU"
      id: "1E27"
    - name: "TS"
      cardType: "GPU"
      id: "1E3E"