apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role
rules:
  - apiGroups:
      - batch
    resources:
      - job
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - bocloud.com
    resources:
      - gpunodes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bocloud.com
    resources:
      - gpunodes/finalizers
    verbs:
      - update
  - apiGroups:
      - bocloud.com
    resources:
      - gpunodes/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/status
    verbs:
      - watch
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - update
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - batch.volcano.sh
    resources:
      - jobs
    verbs:
      - get
      - list
