---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: helm-controller
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-controller
subjects:
- kind: ServiceAccount
  name: helm-controller
  namespace: kube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: helm-controller
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: helm-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helm-controller
    app.kubernetes.io/version: 1.6.0
    helm.sh/chart: helm-controller-1.6.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: helm-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helm-controller
    app.kubernetes.io/version: 1.6.0
    helm.sh/chart: helm-controller-1.6.0
  name: helm-controller
  namespace: kube-system
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: helm-controller
      app.kubernetes.io/name: helm-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: helm-controller
        app.kubernetes.io/name: helm-controller
    spec:
      containers:
      - args:
        - --zap-devel=true
        - --job-image={{ .repo }}helm-install:1.6.13
        - --job-image-pull-policy=IfNotPresent
        - --job-requests-cpu=50m
        - --job-requests-memory=64Mi
        - --job-limits-cpu=100m
        - --job-limits-memory=128Mi
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: helm-controller
        image: {{ .repo }}helm-controller:1.6.13
        imagePullPolicy: IfNotPresent
        name: helm-controller
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext: {}
      securityContext: {}
      serviceAccount: helm-controller
      serviceAccountName: helm-controller
