apiVersion: v1
data:
  generic-exporter.yml: ""
kind: ConfigMap
metadata:
  name: generic-exporter-config
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: generic-exporter
  name: generic-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 10082
      targetPort: 10082
  selector:
    name: generic-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: generic-exporter
  name: generic-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scheme: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: generic-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-exporter
  namespace: monitoring
  labels:
    kubernetes.customized/cluster_component_prometheus: generic-exporter
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      name: generic-exporter
  template:
    metadata:
      labels:
        name: generic-exporter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: {{ .repo }}mini-generic-exporter:v1.0.3
          name: generic-exporter
          ports:
            - containerPort: 10082
              name: http
          resources:
            requests:
              memory: 50Mi
          volumeMounts:
            - mountPath: /opt/generic-config
              name: config
              readOnly: false
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: prometheus-operator
      volumes:
        - configMap:
            name: generic-exporter-config
          name: config
