---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
  labels:
    kubernetes.customized/cluster_component_kubevirt: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - HardDisk
        - DataVolumes
        - HostDisk
        - ExpandDisks
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  imageRepository: {{.repo}}kubevirt
  workloadUpdateStrategy: {}
