apiVersion: v1
kind: ConfigMap
metadata:
  name: bkeagent-launcher-kubeconfig
  namespace: kube-system
data:
  config: |
    {{ indent .kubeconfig "    " }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bkeagent-launcher
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bkeagent
  template:
    metadata:
      labels:
        app: bkeagent
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists

      restartPolicy: Always
      hostNetwork: true
      hostIPC: true
      hostPID: true
      containers:
        - command:
            - launcher
            - --kubeconfig=/etc/openFuyao/bkeagent/config
            - --ntp-server={{ .ntpServer }}
            - --health-port={{ .agentHealthPort }}
            - --debug={{ .debug }}
          env:
            - name: container
              value: "true"
          image: {{ .launcherImage }}
          imagePullPolicy: Always
          name: bkeagent
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/openFuyao/bkeagent/launcher
              name: bkeagent-launcher
            - mountPath: /etc/openFuyao/bkeagent/
              name: bkeagent-launcher-kubeconfig
          readinessProbe:
            httpGet:
              port: 3377
              path: /readyz
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 2
      volumes:
        - name: bkeagent-launcher
          hostPath:
            path: /etc/openFuyao/bkeagent/launcher
            type: DirectoryOrCreate
        - name: bkeagent-launcher-kubeconfig
          configMap:
            name: bkeagent-launcher-kubeconfig


