apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fabric
  namespace: monitoring
  labels:
    app: fabric-node
spec:
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: api
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: fabric-node
      