{{ $scriptDir := "/etc/openFuyao/bkeagent/scripts/" }}

apiVersion: bkeagent.bocloud.com/v1beta1
kind: Command
metadata:
  name: kernel-optimize
  namespace: {{.namespace}}
spec:
  # 挂起暂不执行，可阻止下个执行的指令
  suspend: false
  commands:
    - backoffDelay: 3
      command:
        - "configmap:cluster-system/kernel.sh:ro:{{$scriptDir}}kernel.sh"
      id: save-kernel-script
      type: Kubernetes
    - backoffDelay: 3
      command:
        - "chmod +x {{$scriptDir}}kernel.sh"
      id: chmod-script
      type: Shell
    - backoffDelay: 10
      command:
        - "{{$scriptDir}}kernel.sh"
      id: run-script
      type: Shell
  backoffLimit: 3
  nodeSelector:
    matchLabels:
    {{- $ips := split .nodesIps "," }}
    {{- range $ips }}
      {{ . }}: {{ . }}
    {{- end }}